version: "3"
services:
  flask:
    build: .
    container_name: flask
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:4.0.4-alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"