version: "3"
services:
  flask:
    image: 104466/app-image
    build: .
    container_name: flask
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:4.0.4-alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  worker:
      image: 104466/app-image
      depends_on:
          - redis
      command: rq worker --url redis://redis:6379 &
      deploy:
        replicas: 10
      links:
          - redis
